language: ruby
cache:
  - bundler
  - apt
rvm:
  - 2.0.0-p598
  - 2.1.5
  - 2.2.0
bundler_args: --without development production --quiet --jobs=3 --retry=3
addons:
  postgresql: "9.3"
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libicu-dev
before_script:
  - cp -r .env.travis .env
script:
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate db:seed spec
