defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] || 'zumhotface' %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>

development:
  <<: *defaults

test:
  <<: *defaults
  database: <%= ENV['TRAVIS'] == 'yes' ? ENV['DB_NAME'] : 'zumhotface_test' %>

production:
  <<: *defaults
