defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *defaults

test:
  <<: *defaults
  database: <%= ENV['TRAVIS'] == 'yes' ? ENV['DB_NAME'] : 'zumhotface_test' %>

production:
  <<: *defaults
