defaults: &defaults
  server:
    host: <%= ENV['ZHF_HOST'] || 'localhost' %>
    port: <%= ENV['ZHF_PORT'] || 3000 %>
    pid: <%= ENV['ZHF_PID'] %>
    log: <%= ENV['ZHF_LOG'] %>
    workers: <%= ENV['ZHF_UNICORN_WORKERS'] || 4 %>
  mail:
    from: <%= ENV['ZHF_MAIL_FROM'] %>
    admin: <%= ENV['ZHF_ADMIN_EMAIL'] %>
  uploads:
    directory: <%= ENV['ZHF_DATA_DIRECTORY'] || ':rails_root/public/system' %>
    secret_key: <%= ENV['ZHF_SECRET_KEY'] %>
    aws_s3:
      bucket: <%= ENV['AWS_BUCKET'] %>
      s3_credentials:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise:
    secret_key: <%= ENV['ZHF_SECRET_KEY'] %>
  redis:
    host: <%= ENV['REDIS_HOST'] %>
    port: <%= ENV['REDIS_PORT'] %>
    database: <%= ENV['REDIS_DATABASE'] %>
    namespace: <%= ENV['REDIS_NAMESPACE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
